### ISSUE TITLE
RCP visualization services should extend the startup extension point

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/eavp#157]
The service factory and the RCP visualization services should extend the org.eclipse.ui.startup extension point and set themselves to auto-start, so that EAVP will be able to provide file opening services like CSV or VisIt when installed through the Install New Software wizard.

**Comment by jayjaybillings** [comment]
I believe this is the output from this bug:
![screenshot from 2017-10-21 09-20-27](https://user-images.githubusercontent.com/6378849/31852189-77b71832-b641-11e7-8399-ed38f275e99c.png)

**Comment by jonahgraham** [comment]
Try to avoid org.eclipse.ui.startup if possible. This should be solvable with OSGi declarative services so the service is started when needed, rather than all the time.

**Comment by jayjaybillings** [comment]
Thanks @jonahkichwacoders.

OSGi DS is the way that I would like to do it and all of these services are already DS-enabled. However, OSGi DS has always had a problem that bundles are generally not loaded - at least in our products - without auto-starting them in a product configuration. I've never figured out how to get around this. The way these bundles work in ICE is that they are set to auto-start in the product configuration at run level 4 (I think). We had to take even more drastic measures where org.eclipse.core.resources is involved because it is so ridiculously tied to the startup order of the workbench. So I have always thought of this as more of a limitation of the platform than something we can fix.

That is possibly the longest, most defensive way I can possible say: I would appreciate any suggestions that you have! :-)

**Comment by SmithRWORNL** [comment]
EAVP will be converted to an http micro service using the HATEOS principle instead of an OSGI service in 0.3
