### ISSUE TITLE
TimeSlider widget is out of sync with VisIt

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#22]
If you render the wave example with VisIt, turn off looping and then watch the time slider, then you will see that it stops long before the VisIt render process stops. This is also true if you change the frame rate.

**Comment by SmithRWORNL** [comment]
I cannot reproduce this behavior on my machine. After the time slider reaches the far right side, the VisIt model continues updating just long enough to push the final change to the last timestep. 

It's possible that this was caused by some computers taking longer to render a new timestep than it took for the time slider to advance to the next step. It's possible that 36073f0d33483e85c166206c9acd37e4fffbf35f would have resolved this. Try the latest EAVP version on the machine that was experiencing this bug and see if it is still occurring.
