### ISSUE TITLE
Path for VisIt connection

### ISSUE THREAD

**Issue by kburova** [eclipse/eavp#35]
When we specify a path for Visit connection, it requires that user provides full path like ~/.../Applications/VisIt.app/Contents/Resources/bin. This might be complicated and if user makes a mistake he can get into another bug #34. 
The idea is to fix it so user has to specify the path only till .../VisIt.app and ICE completes the rest.

Another issue with the path is that when we click '+' to add a new path, we need to make sure that correct path is given. For example, the path i'm given doesn't even have Visit folder in it. It can be confusing a bit.

**Comment by amccaskey** [comment]
And just to note - this is for Mac.

**Comment by SmithRWORNL** [comment]
The first problem was actually an issue with documentation, as the VisIt Java client will automatically handle the case of being given /Applications instead of /Applications/VisIt.app/Contents/Resources/bin. I've updated the documentation to give people the simpler path.

For the second issue, the VisIt Preferences page will now give useful default paths as of commit 6b54dc8cc224446169dbf8e272af1b5c7a2f7327.
