### ISSUE TITLE
MeshDescriptionTester.checkPackaging is broken and badly written

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#52]
org.eclipse.ice.eavp.viz.service.mesh.datastructures.test.MeshDescriptionTester.checkPackaging() is broken. The build fails at line 286. Furthermore, the checkPackaging operation is badly written.

We need:
1.) Implement a helper operation that creates the mesh described between lines 68-195.
2.) To fix the assertion at 286 by having a separate operation - MeshDescriptionTester.checkEquality() - that insures that two separate MeshDescriptions can be equal to each other when created from meshes generated using the helper function created in 1 above. We should not be testing that IController is equal to BasicController here! That test is presumably done in BasicControllerTester. This means that MeshDescription needs equals, copy, clone and hashCode implemented. Further more MeshDescription should implement IMeshDescription so that copy() can take an interface instead of a base class.
3.) To move the test for persistence to its own operation that only tests persistence. The final line will be the same as line 286, but the difference is that we will be able to check if equals() is the problem using the operation implemented in 2 or if the JAXB (un)marshalling is the problem.

I have commented out line 286 for the moment because this is breaking EAVP and upstream builds like ICE.

**Comment by SmithRWORNL** [comment]
Fixed by commit 941a6d746c3e16dbc0f79411b483d97a8d6c1475. However, continuing to test for equality between IControllers was still necessary for the checkPackaging operation, as the ability to compress an IController into a MeshDescription and retrieve it without any information being lost or changed is important and non-trivial functionality for the MeshDescription class, and equality testing is the most maintainable way to test it. The test for persistence was able to be switched to a comparison of two MeshDescriptions, though.

**Comment by jayjaybillings** [comment]
Looks good to me. Good work.
