### ISSUE TITLE
Implement ASCIISTLGeometryImporter in jay/model

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#57]
The jay/model branch contains new data structures for managing geometries. All of these data structures are based on an EMF model. This model also contains an IGeometryImporter interface. We need to implement this interface for ASCII-based STL files. 

You can do this in the branch. The ASCIISTLGeometryImporterImpl.java class is already generated. Pay attention that:
1.) You follow the instructions to prevent the operation from being overwritten, namely the comment "// Ensure that you remove @generated or mark it @generated NOT." I prefer that you use @generated NOT
2.) You update the model, not the source code, with the default value for the description.
3.) You figure out the proper way to fill the fileTypes array, and, preferably, mark it final so that it can't be changed. This should also be done in the model.
4.) Break up the import into multiple functions instead of putting all calls into load(). For example, you can have functions like createTriangleFromString() and loadShapes() that are called as part of load().

Any changes to the model will require regenerating the model and edit code. You should also generate tests for these bundles using the genmodel, and then implement a test for ASCIISTLGeometryImporterImpl.java.

**Comment by KasperGam** [comment]
I have implemented this functionality in my branch and added a test bundle, but I renamed the ASCIISTLGeometryImporter to STLGeometryImporter, adding binary support in the load(Path) function as well as ASCII support. The xtext files were moved inside the model bundle, as they now use the new ecore model rather than generate their own, and having those files in a different project causes dependency loops. Look at KasperGam/eavp/ in the kasper/model branch.
1.) I used @generated NOT
2.) Updated the description for the new STL importer
3.) Unfortunately, it does not seem that an inherited property can have a default value set in the model. This we might have to do programmatically, as the FileTypes() array is declared in IGeometryImporter, and the model does not seem to allow setting these inherited values. 
4.) The method first loads the xText Geometry (only around 10 lines), and if that was successful, it returns that. Otherwise, it loads the binary form of STL in a separate method called loadBinary(Path), which takes around 55 lines to parse and assign values to the model from the file's input. 

There is a test bundle with a test for STLGeometryImporter that covers both ASCII and binary files.

**Comment by jayjaybillings** [comment]
Great! How about submitting a pull request?

**Comment by jayjaybillings** [comment]
I couldn't accept #60 because of various issues. Kasper is working on addressing them.

**Comment by SmithRWORNL** [comment]
A new pull request was issued, and as of commit 0b1bbd9317bfeddbd5373b6df195473e0c4525e0 this has been merged into next.
